<?php
session_start();

// Check if user is logged in
$is_logged_in = isset($_SESSION['loggedin']) && $_SESSION['loggedin'] === true;
$is_admin_logged_in = isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true;

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>GenAIWear</title>
    <link rel="stylesheet" href="style.css">
    
</head>

<body>

    <header>
        <h1>Welcome to GenAIWear</h1>
    </header>

    <nav>
        <a href="#" onclick="showSection('home')">Home</a>
        <a href="#" onclick="showSection('about')">About</a>
        <a href="#" onclick="showSection('products')">Products/Services</a>
        <a href="#" onclick="showSection('news')">News</a>
        <a href="#" onclick="showSection('contacts')">Contacts</a>
        <a href="#" onclick="showSection('search')">Users</a>
    </nav>

    <div id="content">
        <section id="home" class="active">
            <h2>Home</h2>
            <p>Welcome to GenAIWear, the future of fashion and technology. We blend cutting-edge AI algorithms with fashion design to create clothing that is not just unique but revolutionary.</p>
            <p>Step into a new world where fashion meets technology. Experience the inimitable style only possible through the power of artificial intelligence.</p>
        </section>

        <section id="about">
            <h2>About Us</h2>
            <p>At GenAIWear, we're not just crafting clothing; we're crafting the future. We leverage state-of-the-art Artificial Intelligence technologies to create unique, stylish, and personalized clothing that sets you apart. Our innovative designs are generated by complex neural networks trained on a diverse dataset comprising decades of fashion trends, art, and cultural influences.</p>

<p>Our AI algorithms have learned the essence of style from the history of fashion itself, assimilating everything from vintage elegance to contemporary chic. This enables us to produce clothing that isn't just fashionable, but also deeply personalized and incredibly diverse. Whether you're seeking the sophistication of classic style or the edginess of modern trends, our AI-powered designs offer something for everyone.</p>

<p>The result is a revolutionary approach to fashion that's as dynamic and unique as you are. With GenAIWear, you're not just wearing a piece of clothing; you're wearing a piece of technology, a piece of art, and a piece of the future.</p>
        </section>

        <section id="products">
            <h2>Products/Services</h2>
            <p>We offer a range of AI-generated clothing including T-shirts, hoodies, and more.</p>
            <button onclick="generateAIImages()">Generate AI Images</button>
            <div>
    <!-- Link styled as a button for most viewed products -->
    <a href="most_viewed.php" class="button">Show Top 5 Most Viewed Products</a>

    <!-- Link styled as a button for recently viewed products -->
    <a href="recently_viewed.php" class="button">Show Last 5 Previously Viewed Products</a>
</div>
            <h3>Hoodies</h3>
            <div id="product-details">
            <div class="product-grid">
                <div class="product-item" data-product-id="1" href="/products/product1.php">
                    <a href="products/product1.php">
                    <img src="images/neon_dream_hoodie.png" alt="Neon Dragon Hoodie">
                    <p>Neon Dream</p>
                </a>
                </div>
                <div class="product-item" data-product-id="2">
                    <a href="products/product2.php">
                    <img src="images/cybernetic_pulse_hoodie.png" alt="Cybernetic Sakura Hoodie">
                    <p>Cybernetic Pulse</p>
                </a>
                </div>
                <div class="product-item" data-product-id="3">
                    <a href="products/product3.php">
                    <img src="images/ai_revolution_hoodie.png" alt="AI Tokyo Hoodie">
                    <p>AI Revolution</p>
                </a>
                </div>
                <div class="product-item" data-product-id="4">
                    <a href="products/product4.php">
                    <img src="images/hoodie 1.png" alt="Neon Nomad Hoodie">
                    <p>Neon Nomad Hoodie</p>
                </a>
                </div>
            </div>
            <div class="product-grid">
                <div class="product-item" data-product-id="5">
                    <a href="products/product5.php">
                    <img src="images/hoodie 2.png" alt="Matrix Mirage">
                    <p>Matrix Mirage</p>
                </a>
                </div>
                <div class="product-item" data-product-id="6">
                    <a href="products/product6.php">
                    <img src="images/hoodie 3.png" alt="HoloHood Vanguard">
                    <p>HoloHood Vanguard</p>
                </a>
                </div>
                <div class="product-item" data-product-id="7" >
                    <a href="products/product7.php">
                    <img src="images/hoodie 4.png" alt="CyberCore Cloak">
                    <p>CyberCore Cloak</p>
                </a>
                </div>
                <div class="product-item" data-product-id="8">
                    <a href="products/product8.php">
                    <img src="images/hoodie 5.png" alt="Synthwave Sentry">
                    <p>Synthwave Sentry</p>
                </a>
                </div>
            </div>
            <div class="product-grid">
                <div class="product-item" data-product-id="9" >
                    <a href="products/product9.php">
                    <img src="images/hoodie 6.png" alt="Digital Drifter">
                    <p>Digital Drifter</p>
                </a>
                </div>
                <div class="product-item" data-product-id="10">
                    <a href="products/product10.php">
                    <img src="images/hoodie 7.png" alt="Quantum Quester">
                    <p>Quantum Quester</p>
                </a>
                </div>
            </div>
                </div>
            </ul>
        </section>

        <section id="news">
            <h2>Latest News</h2>
            <p>We just launched our new summer collection featuring AI-generated designs that are out of this world!</p>
        </section>

        <section id="contacts">
            
            <h2>Contact Us</h2>
            <?php include 'contacts.php'; ?>
    </section>
    




<section id="search">
    <h2>Search Users</h2>
    <button class="button" onclick="location.href='curl.php';">View All Users</button>
    <form action="/search_db.php" method="POST">
    <label><input type="first_name" name="first_name" placeholder="first name"></label>
    <label><input type="last_name" name="last_name" placeholder="last name"></label>
    <label><input type="email" name="email" placeholder="email address"></label>
    <label><input type="home_phone" name="home_phone" placeholder="home phone number"></label>
    <label><input type="cell_phone" name="cell_phone" placeholder="cell phone number"></label>
    <br>
    <br>
    <input type="submit" value="Search">
    </form>
</section>

    
        </section>
    </div>

    <footer>
        <p>&copy; 2023 GenAIWear</p>
    </footer>
<script src="script.js"></script>
</body>
</html>
